// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const KIMI_CODING_MODELS = {
	"kimi-for-coding": {
		id: "kimi-for-coding",
		name: "Kimi For Coding",
		api: "anthropic-messages",
		provider: "kimi-coding",
		baseUrl: "https://api.kimi.com/coding",
		headers: {
			"User-Agent": "KimiCLI/1.5",
		},
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 3,
			output: 15,
			cacheRead: 0.3,
			cacheWrite: 0,
		},
		contextWindow: 1048576,
		maxTokens: 131072,
	} satisfies Model<"anthropic-messages">,
} as const;